---
  debug: false
  log-level: "OFF"
  server-port: 1433
  server-name: qflock-jdbc-dc2
# Uncomment the below line for debug.  Use args --mode local --debug_pyspark
#  server-name: <host ip>
  compression: true
  spark:
    master: local[2]
    hive-metastore: "qflock-storage-dc1"
    hive-metastore-port: "9084"
    conf:
    - spark.driver.maxResultSize=2g
    - spark.driver.memory=12g
    - spark.executor.memory=12g
    - spark.sql.execution.arrow.pyspark.enabled=true
    - spark.sql.catalogImplementation=hive
    - spark.sql.warehouse.dir=hdfs://qflock-storage-dc1:9000/user/hive/warehouse3
    - 'spark.driver.extraJavaOptions=-classpath /conf/:/opt/spark-3.2.1/jars/*: -agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=172.24.0.3:5006'
    jars:
    - /extensions/target/scala-2.12/qflock-extensions_2.12-0.1.0.jar

